// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/answer"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/predicate"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/question"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/response"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/selectedoption"
	"github.com/google/uuid"
)

// AnswerUpdate is the builder for updating Answer entities.
type AnswerUpdate struct {
	config
	hooks    []Hook
	mutation *AnswerMutation
}

// Where appends a list predicates to the AnswerUpdate builder.
func (au *AnswerUpdate) Where(ps ...predicate.Answer) *AnswerUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetQuestionID sets the "question_id" field.
func (au *AnswerUpdate) SetQuestionID(u uuid.UUID) *AnswerUpdate {
	au.mutation.SetQuestionID(u)
	return au
}

// SetNillableQuestionID sets the "question_id" field if the given value is not nil.
func (au *AnswerUpdate) SetNillableQuestionID(u *uuid.UUID) *AnswerUpdate {
	if u != nil {
		au.SetQuestionID(*u)
	}
	return au
}

// SetResponseID sets the "response_id" field.
func (au *AnswerUpdate) SetResponseID(u uuid.UUID) *AnswerUpdate {
	au.mutation.SetResponseID(u)
	return au
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (au *AnswerUpdate) SetNillableResponseID(u *uuid.UUID) *AnswerUpdate {
	if u != nil {
		au.SetResponseID(*u)
	}
	return au
}

// SetAnswerText sets the "answer_text" field.
func (au *AnswerUpdate) SetAnswerText(s string) *AnswerUpdate {
	au.mutation.SetAnswerText(s)
	return au
}

// SetNillableAnswerText sets the "answer_text" field if the given value is not nil.
func (au *AnswerUpdate) SetNillableAnswerText(s *string) *AnswerUpdate {
	if s != nil {
		au.SetAnswerText(*s)
	}
	return au
}

// SetQuestion sets the "question" edge to the Question entity.
func (au *AnswerUpdate) SetQuestion(q *Question) *AnswerUpdate {
	return au.SetQuestionID(q.ID)
}

// SetResponse sets the "response" edge to the Response entity.
func (au *AnswerUpdate) SetResponse(r *Response) *AnswerUpdate {
	return au.SetResponseID(r.ID)
}

// AddSelectedOptionIDs adds the "selectedOption" edge to the SelectedOption entity by IDs.
func (au *AnswerUpdate) AddSelectedOptionIDs(ids ...int) *AnswerUpdate {
	au.mutation.AddSelectedOptionIDs(ids...)
	return au
}

// AddSelectedOption adds the "selectedOption" edges to the SelectedOption entity.
func (au *AnswerUpdate) AddSelectedOption(s ...*SelectedOption) *AnswerUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return au.AddSelectedOptionIDs(ids...)
}

// Mutation returns the AnswerMutation object of the builder.
func (au *AnswerUpdate) Mutation() *AnswerMutation {
	return au.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (au *AnswerUpdate) ClearQuestion() *AnswerUpdate {
	au.mutation.ClearQuestion()
	return au
}

// ClearResponse clears the "response" edge to the Response entity.
func (au *AnswerUpdate) ClearResponse() *AnswerUpdate {
	au.mutation.ClearResponse()
	return au
}

// ClearSelectedOption clears all "selectedOption" edges to the SelectedOption entity.
func (au *AnswerUpdate) ClearSelectedOption() *AnswerUpdate {
	au.mutation.ClearSelectedOption()
	return au
}

// RemoveSelectedOptionIDs removes the "selectedOption" edge to SelectedOption entities by IDs.
func (au *AnswerUpdate) RemoveSelectedOptionIDs(ids ...int) *AnswerUpdate {
	au.mutation.RemoveSelectedOptionIDs(ids...)
	return au
}

// RemoveSelectedOption removes "selectedOption" edges to SelectedOption entities.
func (au *AnswerUpdate) RemoveSelectedOption(s ...*SelectedOption) *AnswerUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return au.RemoveSelectedOptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AnswerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AnswerUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AnswerUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AnswerUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AnswerUpdate) check() error {
	if _, ok := au.mutation.QuestionID(); au.mutation.QuestionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Answer.question"`)
	}
	if _, ok := au.mutation.ResponseID(); au.mutation.ResponseCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Answer.response"`)
	}
	return nil
}

func (au *AnswerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(answer.Table, answer.Columns, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.AnswerText(); ok {
		_spec.SetField(answer.FieldAnswerText, field.TypeString, value)
	}
	if au.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ResponseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.ResponseTable,
			Columns: []string{answer.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ResponseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.ResponseTable,
			Columns: []string{answer.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.SelectedOptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.SelectedOptionTable,
			Columns: []string{answer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedoption.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedSelectedOptionIDs(); len(nodes) > 0 && !au.mutation.SelectedOptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.SelectedOptionTable,
			Columns: []string{answer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.SelectedOptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.SelectedOptionTable,
			Columns: []string{answer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AnswerUpdateOne is the builder for updating a single Answer entity.
type AnswerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnswerMutation
}

// SetQuestionID sets the "question_id" field.
func (auo *AnswerUpdateOne) SetQuestionID(u uuid.UUID) *AnswerUpdateOne {
	auo.mutation.SetQuestionID(u)
	return auo
}

// SetNillableQuestionID sets the "question_id" field if the given value is not nil.
func (auo *AnswerUpdateOne) SetNillableQuestionID(u *uuid.UUID) *AnswerUpdateOne {
	if u != nil {
		auo.SetQuestionID(*u)
	}
	return auo
}

// SetResponseID sets the "response_id" field.
func (auo *AnswerUpdateOne) SetResponseID(u uuid.UUID) *AnswerUpdateOne {
	auo.mutation.SetResponseID(u)
	return auo
}

// SetNillableResponseID sets the "response_id" field if the given value is not nil.
func (auo *AnswerUpdateOne) SetNillableResponseID(u *uuid.UUID) *AnswerUpdateOne {
	if u != nil {
		auo.SetResponseID(*u)
	}
	return auo
}

// SetAnswerText sets the "answer_text" field.
func (auo *AnswerUpdateOne) SetAnswerText(s string) *AnswerUpdateOne {
	auo.mutation.SetAnswerText(s)
	return auo
}

// SetNillableAnswerText sets the "answer_text" field if the given value is not nil.
func (auo *AnswerUpdateOne) SetNillableAnswerText(s *string) *AnswerUpdateOne {
	if s != nil {
		auo.SetAnswerText(*s)
	}
	return auo
}

// SetQuestion sets the "question" edge to the Question entity.
func (auo *AnswerUpdateOne) SetQuestion(q *Question) *AnswerUpdateOne {
	return auo.SetQuestionID(q.ID)
}

// SetResponse sets the "response" edge to the Response entity.
func (auo *AnswerUpdateOne) SetResponse(r *Response) *AnswerUpdateOne {
	return auo.SetResponseID(r.ID)
}

// AddSelectedOptionIDs adds the "selectedOption" edge to the SelectedOption entity by IDs.
func (auo *AnswerUpdateOne) AddSelectedOptionIDs(ids ...int) *AnswerUpdateOne {
	auo.mutation.AddSelectedOptionIDs(ids...)
	return auo
}

// AddSelectedOption adds the "selectedOption" edges to the SelectedOption entity.
func (auo *AnswerUpdateOne) AddSelectedOption(s ...*SelectedOption) *AnswerUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return auo.AddSelectedOptionIDs(ids...)
}

// Mutation returns the AnswerMutation object of the builder.
func (auo *AnswerUpdateOne) Mutation() *AnswerMutation {
	return auo.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (auo *AnswerUpdateOne) ClearQuestion() *AnswerUpdateOne {
	auo.mutation.ClearQuestion()
	return auo
}

// ClearResponse clears the "response" edge to the Response entity.
func (auo *AnswerUpdateOne) ClearResponse() *AnswerUpdateOne {
	auo.mutation.ClearResponse()
	return auo
}

// ClearSelectedOption clears all "selectedOption" edges to the SelectedOption entity.
func (auo *AnswerUpdateOne) ClearSelectedOption() *AnswerUpdateOne {
	auo.mutation.ClearSelectedOption()
	return auo
}

// RemoveSelectedOptionIDs removes the "selectedOption" edge to SelectedOption entities by IDs.
func (auo *AnswerUpdateOne) RemoveSelectedOptionIDs(ids ...int) *AnswerUpdateOne {
	auo.mutation.RemoveSelectedOptionIDs(ids...)
	return auo
}

// RemoveSelectedOption removes "selectedOption" edges to SelectedOption entities.
func (auo *AnswerUpdateOne) RemoveSelectedOption(s ...*SelectedOption) *AnswerUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return auo.RemoveSelectedOptionIDs(ids...)
}

// Where appends a list predicates to the AnswerUpdate builder.
func (auo *AnswerUpdateOne) Where(ps ...predicate.Answer) *AnswerUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AnswerUpdateOne) Select(field string, fields ...string) *AnswerUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Answer entity.
func (auo *AnswerUpdateOne) Save(ctx context.Context) (*Answer, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AnswerUpdateOne) SaveX(ctx context.Context) *Answer {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AnswerUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AnswerUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AnswerUpdateOne) check() error {
	if _, ok := auo.mutation.QuestionID(); auo.mutation.QuestionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Answer.question"`)
	}
	if _, ok := auo.mutation.ResponseID(); auo.mutation.ResponseCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Answer.response"`)
	}
	return nil
}

func (auo *AnswerUpdateOne) sqlSave(ctx context.Context) (_node *Answer, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(answer.Table, answer.Columns, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Answer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, answer.FieldID)
		for _, f := range fields {
			if !answer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != answer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.AnswerText(); ok {
		_spec.SetField(answer.FieldAnswerText, field.TypeString, value)
	}
	if auo.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ResponseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.ResponseTable,
			Columns: []string{answer.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ResponseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.ResponseTable,
			Columns: []string{answer.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.SelectedOptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.SelectedOptionTable,
			Columns: []string{answer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedoption.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedSelectedOptionIDs(); len(nodes) > 0 && !auo.mutation.SelectedOptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.SelectedOptionTable,
			Columns: []string{answer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.SelectedOptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answer.SelectedOptionTable,
			Columns: []string{answer.SelectedOptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedoption.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Answer{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
