// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/predicate"
	"github.com/KinjiKawaguchi/Coteacher/coteacher-server/domain/repository/ent/textquestion"
)

// TextQuestionDelete is the builder for deleting a TextQuestion entity.
type TextQuestionDelete struct {
	config
	hooks    []Hook
	mutation *TextQuestionMutation
}

// Where appends a list predicates to the TextQuestionDelete builder.
func (tqd *TextQuestionDelete) Where(ps ...predicate.TextQuestion) *TextQuestionDelete {
	tqd.mutation.Where(ps...)
	return tqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tqd *TextQuestionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tqd.sqlExec, tqd.mutation, tqd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tqd *TextQuestionDelete) ExecX(ctx context.Context) int {
	n, err := tqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tqd *TextQuestionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(textquestion.Table, sqlgraph.NewFieldSpec(textquestion.FieldID, field.TypeUUID))
	if ps := tqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tqd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tqd.mutation.done = true
	return affected, err
}

// TextQuestionDeleteOne is the builder for deleting a single TextQuestion entity.
type TextQuestionDeleteOne struct {
	tqd *TextQuestionDelete
}

// Where appends a list predicates to the TextQuestionDelete builder.
func (tqdo *TextQuestionDeleteOne) Where(ps ...predicate.TextQuestion) *TextQuestionDeleteOne {
	tqdo.tqd.mutation.Where(ps...)
	return tqdo
}

// Exec executes the deletion query.
func (tqdo *TextQuestionDeleteOne) Exec(ctx context.Context) error {
	n, err := tqdo.tqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{textquestion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tqdo *TextQuestionDeleteOne) ExecX(ctx context.Context) {
	if err := tqdo.Exec(ctx); err != nil {
		panic(err)
	}
}
